/*
==========================================================
Retail Sales Analytics Dashboard
SQL Business Analysis
Author : Bhumireddy Masthanreddy
==========================================================
*/

/*
Business Question 1
-------------------
What is the total sales revenue generated by the company?
*/
SELECT
    SUM(UnitPrice * Quantity * (1 - Discount)) AS TotalSales
FROM [Order Details];

/*
Business Question 2
-------------------
Which are the Top 10 selling products based on total sales?
*/
SELECT
    ProductName,
    SUM(UnitPrice * Quantity * (1 - Discount)) AS TotalSales
FROM [Order Details] od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY ProductName
ORDER BY TotalSales DESC
LIMIT 10;


/*
Business Question 3
-------------------
Who are the Top 10 customers based on total purchase amount?
*/
SELECT
    c.CompanyName,
    SUM(UnitPrice * Quantity * (1 - Discount)) AS TotalSales
FROM [Order Details] od
JOIN Orders o ON od.OrderID = o.OrderID
JOIN Customers c ON o.CustomerID = c.CustomerID
GROUP BY c.CompanyName
ORDER BY TotalSales DESC
LIMIT 10;


/*
Business Question 4
-------------------
What is the monthly sales trend?
*/
SELECT
    MONTH(o.OrderDate) AS Month,
    SUM(UnitPrice * Quantity * (1 - Discount)) AS TotalSales
FROM [Order Details] od
JOIN Orders o ON od.OrderID = o.OrderID
GROUP BY MONTH(o.OrderDate)
ORDER BY Month;


/*
Business Question 5
-------------------
Which product categories generate the highest sales?
*/
SELECT
    c.CategoryName,
    SUM(UnitPrice * Quantity * (1 - Discount)) AS TotalSales
FROM [Order Details] od
JOIN Products p ON od.ProductID = p.ProductID
JOIN Categories c ON p.CategoryID = c.CategoryID
GROUP BY c.CategoryName
ORDER BY TotalSales DESC;



/*
Business Question 6
-------------------
Which countries generate the highest sales revenue?
*/
SELECT
    o.ShipCountry,
    SUM(UnitPrice * Quantity * (1 - Discount)) AS TotalSales
FROM [Order Details] od
JOIN Orders o ON od.OrderID = o.OrderID
GROUP BY o.ShipCountry
ORDER BY TotalSales DESC;


/*
Business Question 7
-------------------
How much discount is given across different products?
*/
SELECT
    p.ProductName,
    SUM(Discount) AS TotalDiscount
FROM [Order Details] od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalDiscount DESC;


/*
Business Question 8
-------------------
What is the average order value?
*/
SELECT
    AVG(OrderTotal) AS AverageOrderValue
FROM (
    SELECT
        o.OrderID,
        SUM(UnitPrice * Quantity * (1 - Discount)) AS OrderTotal
    FROM [Order Details] od
    JOIN Orders o ON od.OrderID = o.OrderID
    GROUP BY o.OrderID
) AS OrderSummary;


/*
Business Question 9
-------------------
Which employees handled the highest number of orders?
*/
SELECT
    e.EmployeeID,
    e.FirstName,
    e.LastName,
    COUNT(o.OrderID) AS OrdersHandled
FROM Orders o
JOIN Employees e ON o.EmployeeID = e.EmployeeID
GROUP BY e.EmployeeID, e.FirstName, e.LastName
ORDER BY OrdersHandled DESC;


/*
Business Question 10
-------------------
What are the best-selling products by quantity?
*/
SELECT
    p.ProductName,
    SUM(Quantity) AS TotalQuantitySold
FROM [Order Details] od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalQuantitySold DESC
LIMIT 10;

/*